server:
  port: 8083

spring:
  datasource:
    url: '{cipher}AQAtk2Ts4+WgvWtnyFoc2SH7XZ6VZzXfxYWgmOLlgwlDaaFliQgZvi1UsjPhFVhgva0x6scjTZLEErvwbR96hTg64nPq9XLzbeijmAnHPD30dkHVCG0gZ0LIYiVPI2ardirFY2MLYh4xB+0ShYfmcs432xgffkkJKO9Jvz0mh48/5q4Y2Cu9n/9cjEHWCP4h9d6Gx0kDz83mzNoayZMJ7nwzFmVdCmfdZo+Z0gaPccWBUhdqkWue4yAWBO0kVBYqxoKBTpmsCMPHEZYkV67rJk3pn5YOIR3DlTjNMeRUXzsEm1A8gqEf6HcWmn5xgsRMuVAJJDFm1LS0yzgxro2+K5t/bU/u4iK/xKZsJKwyvA+J1VjmjfqImSxCkuDxrEv7O9NVn4EEh90Xtjpt53llrtclG+nCd0O+L/Jh+QjlOI/nocr5fsQ7YYl6AHFjy3cHyWI='
  jpa:
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: lucene/indexes
lucene:
  queryParser:
    leadingWildcard: true

notification:
  ribbon:
    listOfServers: http://localhost:8003