server:
  port: 8083

spring:
  datasource:
    url: '{cipher}AQA6VnDW5Wv7iPyrYHGR8tV6qdJt6CBljFEilPezpU0N7DHXNRLpGvlXT5Liy6f9kcUN4PjTGU9ad1PC1xA3mXXhw4b4OHfy5hpBJpi0hUAuO3Mp/8Q1zGl0l2NTRKtVpbym8s+QN9aqnmOv3PV6/6AcqwQCXmqw0qL/FyQIhKGs7P/GVw1Iywg/e1n/FOPBhIpQT6IGj2wV+BxpMVj9lK0HKm0C3A7xxgPRdpTl7daZe7z5x3EHZla7SuNhXCt95IFrJl952YlZuT3ufgIUxAIzJIkboBpFkgjrh/Vcn5pzRUQ9B4LWc+W1g/Htqcl7EoSRyxtEBDW356m4EJzUgNWXQNyRWDPRPX0/jHseKUs3mXfCSnRLpogn95MERxLobNI77iT9OeFZVtrLSNJb3wtBQBQKOKuuyeHRq85pSL33xoH6PrezDoiF0wyqatGYpTQ='
  jpa:
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: lucene/indexes
lucene:
  queryParser:
    leadingWildcard: true

notification:
  ribbon:
    listOfServers: http://localhost:8003