server:
  port: 8082

spring:
  datasource:
    # url: '{cipher}AQATOnIrCagRmSGfeohEsf7Mf1AFa0fsAE2bYWnmKVDBt7GJKZG9Crq9fUmpfiysns6d+ZEP0H8cztw0KOvpsVtGjY6EgGxB+9iKGlNA8iQsq1zvT9vYtPPPS9ArrPMPZx1XUjNaz2BbhJ1qL7SaVHsgHvYL3vJLWwbkwAfgPoXct6AGDRfX3AZCh+QnwJ/aDBtM0ck4nOJDFsQ6MzM4dPUVIPIY1COj9IwtlKlxGn/HmxCT71K+IqanEmNleb0iWhwszm34h79i8m7Qix+V6fB49YK0RJ8EHOygYsqGLj7VXjGydYLYC4fwnnfKvAJ8J0A9HunfcMzBjqCeZab2XJEbK+ru3CAPHguQeQc+YbZn0Nft4peREXiRvA+tbM0HQgeZ93eh6K2bylSRUR3wJi8g15iHRWtmMOtDc5r9aQImzw=='
    url: '{cipher}AQCNE6PMt37ADNLww9rxaUoAdr+QT3Pe/z67tZEc5fGG3EEAJ7yJJNpfYlM6E/7fFv1/clxp+K1bZmTSMWUhdgfLkdm0A/pWFJj2OqFfdjgDC5qZ5Si3XcFR/+Yq/pvxQ7ExCLUiKCmcrVJRmFAh8SMf706k5HDdDsC/l6s3ht125jOM359mgVB4AE2mjb9tNMZognNfIk2c8pc3IiXBK4ViguUmDlqUiUW2/06WcmixXt9ox688SGSgzpGP4DvSQ0TF0Z+MPnaJoUSovBn6orzjTsXbdocgxBlOuBuE+v6WIoSqtGcHiAe1uhBEgwZ2vCMkYFn6TabSwt4euVYLGvQLaM3Hd2EM0nMpM74IjbFClyyHq+1qI+fB0dT4VniwcmJM0zP+6CwID0LP8KptMs83o8vPvFggGXzcKzsOiLQi6A=='


file:
  storage:
    enabled: true
    bucketName: '{cipher}AQBvoys7ol7k1yaNJJoxWO4Qxvbg3FjXSdTgaXTwEzCGtxGeD2CIu8/JjsF0oEddGsTnG2q+DPrfBTMdTDPDT+UVIpILVIZT/wTgWxoknMLg8gIlidC/2OeysX411CTRcjxX6QihrESWS388kJV+5FZXNA7WO0MM8ciDahXbuuTgxexibXVQOChbdzalKD7g7UCESsEBS5Vu33iRe8/MtKHLPUvYUH5K0FUtLFa2gvYgYQ2XuF1OqkjFdtqeOQlDPy9ZoABFR4BNf3gBT0pth8VaN+xePFwOa/EJUADbMsBSQ51Si9mMp6NBggwj/20+Xkwnwczqt8FoPmAAB8OYz+Z+Uk9v80wn2YlenXX+ipvjpxQThdUwPhIgFjIVOyAVkfhvVctWbP2fuGBY0e+N9+Ha'