server:
  port: 8082

spring:
  datasource:
    # url: '{cipher}AQATOnIrCagRmSGfeohEsf7Mf1AFa0fsAE2bYWnmKVDBt7GJKZG9Crq9fUmpfiysns6d+ZEP0H8cztw0KOvpsVtGjY6EgGxB+9iKGlNA8iQsq1zvT9vYtPPPS9ArrPMPZx1XUjNaz2BbhJ1qL7SaVHsgHvYL3vJLWwbkwAfgPoXct6AGDRfX3AZCh+QnwJ/aDBtM0ck4nOJDFsQ6MzM4dPUVIPIY1COj9IwtlKlxGn/HmxCT71K+IqanEmNleb0iWhwszm34h79i8m7Qix+V6fB49YK0RJ8EHOygYsqGLj7VXjGydYLYC4fwnnfKvAJ8J0A9HunfcMzBjqCeZab2XJEbK+ru3CAPHguQeQc+YbZn0Nft4peREXiRvA+tbM0HQgeZ93eh6K2bylSRUR3wJi8g15iHRWtmMOtDc5r9aQImzw=='
    url: '{cipher}AQApqikhMJlr1WhsLKsHOkCLAt8sTQV48EEaibdp8AYu2+Fhukjep2P6aQURx+dwz7Iz8xlC7mdaxEQNPiNB2fFeGA/brh2X4ZuazQVQb4FBlEXTP/jvj9HJKdNnOcEDNLeBrBXUBuPwau88WV4Cvv4W8rABva4+8Z8oWLq/NiM0KAgSy/2zrWiWGsE0zauM29TgqBaLWdeTex3n+HqUnmEWDvs7yGylAPd6vS363k/AINDrwCyQoMbhukwVZl5G54jp6RoQVs/1MbjSUTY70KtuAmhiYidk3WMy2AX4YGSsj4i+OX6U+pXPG0PYLX68vGprZ/NB/dUs0HrVoC1mrgFX+hIFBMH7W16KQ9xH6+Z2oyXiNIa4ZnLsdZUcd0im+dpUNJBokF9zNc3I/OB7Zi8U75DPPIrZxGKX8H32yrczxw==e'


file:
  storage:
    enabled: true
    bucketName: '{cipher}AQBvoys7ol7k1yaNJJoxWO4Qxvbg3FjXSdTgaXTwEzCGtxGeD2CIu8/JjsF0oEddGsTnG2q+DPrfBTMdTDPDT+UVIpILVIZT/wTgWxoknMLg8gIlidC/2OeysX411CTRcjxX6QihrESWS388kJV+5FZXNA7WO0MM8ciDahXbuuTgxexibXVQOChbdzalKD7g7UCESsEBS5Vu33iRe8/MtKHLPUvYUH5K0FUtLFa2gvYgYQ2XuF1OqkjFdtqeOQlDPy9ZoABFR4BNf3gBT0pth8VaN+xePFwOa/EJUADbMsBSQ51Si9mMp6NBggwj/20+Xkwnwczqt8FoPmAAB8OYz+Z+Uk9v80wn2YlenXX+ipvjpxQThdUwPhIgFjIVOyAVkfhvVctWbP2fuGBY0e+N9+Ha'